import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  title = 'visual';
  chartInfo = [
    {src: 'assets/visual/arc_diagram.svg', name: '弧线图'},
    {src: 'assets/visual/area_graph.svg', name: '面积图'},
    {src: 'assets/visual/bar_graph.svg', name: '条形图'},
    {src: 'assets/visual/box_plot.svg', name: '箱形图'},
    {src: 'assets/visual/brainstorm.svg', name: '脑力激荡图'},
    {src: 'assets/visual/bubble_chart.svg', name: '气泡图'},
    {src: 'assets/visual/bubble_map.svg', name: '气泡地图'},
    {src: 'assets/visual/bullet_chart.svg', name: '子弹图'},
    {src: 'assets/visual/calendar.svg', name: '日历'},
    {src: 'assets/visual/candlestick_chart.svg', name: '蜡烛图'},
    {src: 'assets/visual/chord_diagram.svg', name: '弦图'},
    {src: 'assets/visual/choropleth_map.svg', name: '地区分布图'},
    {src: 'assets/visual/circle_packing.svg', name: '圆堆积'},
    {src: 'assets/visual/connection_map.svg', name: '连接地图'},
    {src: 'assets/visual/density_plot.svg', name: '密度图'},
    {src: 'assets/visual/donut_chart.svg', name: '圆环图'},
    {src: 'assets/visual/point_map.svg', name: '点示地图'},
    {src: 'assets/visual/dot_matrix_chart.svg', name: '点阵图表'},
    {src: 'assets/visual/error_bars.svg', name: '误差线'},
    {src: 'assets/visual/flow_chart.svg', name: '流程图'},
    {src: 'assets/visual/flow_map.svg', name: '流向地图'},
    {src: 'assets/visual/gantt_chart.svg', name: '甘特图'},
    {src: 'assets/visual/heat_map.svg', name: '热图（矩阵'},
    {src: 'assets/visual/histogram.svg', name: '直方图'},
    {src: 'assets/visual/illustration_diagram.svg', name: '说明图'},
    {src: 'assets/visual/kagi_chart.svg', name: '卡吉图'},
    {src: 'assets/visual/line_graph.svg', name: '折线图'},
    {src: 'assets/visual/marimekko_chart.svg', name: '不等宽柱状图'},
    {src: 'assets/visual/multiset_bar_chart.svg', name: '多组条形图'},
    {src: 'assets/visual/network_diagram.svg', name: '网络图'},
    {src: 'assets/visual/nightingale_rose_chart.svg', name: '南丁格尔玫瑰图'},
    {src: 'assets/visual/non_ribbon_chord_diagram.svg', name: '非彩带弦图'},
    {src: 'assets/visual/hikkake_pattern.svg', name: '美国线'},
    {src: 'assets/visual/parallel_coordinates.svg', name: '平行座标图'},
    {src: 'assets/visual/parallel_sets.svg', name: '平行集合图'},
    {src: 'assets/visual/pictogram_chart.svg', name: '象形图'},
    {src: 'assets/visual/pie_chart.svg', name: '饼形图'},
    {src: 'assets/visual/point_and_figure_chart.svg', name: '点数图'},
    {src: 'assets/visual/population_pyramid.svg', name: '人口金字塔'},
    {src: 'assets/visual/proportional_area_chart.svg', name: '比例面积图'},
    {src: 'assets/visual/radar_chart.svg', name: '雷达图'},
    {src: 'assets/visual/radial_bar_chart.svg', name: '径向条形图'},
    {src: 'assets/visual/radial_column_chart.svg', name: '径向柱图'},
    {src: 'assets/visual/sankey_diagram.svg', name: '桑基图'},
    {src: 'assets/visual/scatterplot.svg', name: '散点图'},
    {src: 'assets/visual/span_chart.svg', name: '跨度图'},
    {src: 'assets/visual/condegram_spiral_plot.svg', name: '螺旋图'},
    {src: 'assets/visual/stacked_area_graph.svg', name: '堆叠式面积图'},
    {src: 'assets/visual/stacked_bar_graph.svg', name: '堆叠式条形图'},
    {src: 'assets/visual/stem_and_leaf_plot.svg', name: '茎叶图'},
    {src: 'assets/visual/stream_graph.svg', name: '量化波形图'},
    {src: 'assets/visual/sunburst_diagram.svg', name: '旭日图'},
    {src: 'assets/visual/tally_chart.svg', name: '记数符号图表'},
    {src: 'assets/visual/timeline.svg', name: '时间线'},
    {src: 'assets/visual/time_table.svg', name: '时间表'},
    {src: 'assets/visual/tree_diagram.svg', name: '树形图'},
    {src: 'assets/visual/treemap.svg', name: '树形结构图'},
    {src: 'assets/visual/venn_diagram.svg', name: '文氏图'},
    {src: 'assets/visual/violin_plot.svg', name: '小提琴图'},
    {src: 'assets/visual/word_cloud.svg', name: '字云图'}];

  getSimpleName(src: string) {
    return src.replace('assets/visual/', '').replace('.svg', '').replace('_', ' ');
  }
}
